[versions]
kotlin = "1.9.23"
fabric-loom = "1.6.3"
iridium = "3.1.9"

#reef = "0.1.0"

[libraries]
#reef = { module = "org.teamvoided:reef", version.ref = "reef" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium" }